receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8888" # The collector exposes its own metrics here
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging] # Add other exporters like Jaeger or Zipkin here
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging] # Metrics from your server
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging] # Add other exporters like Loki here
