// Code generated by counterfeiter. DO NOT EDIT.
package messagequeuefakes

import (
	"heimdall/internal/services/messagequeue"
	"sync"
)

type FakeProducer struct {
	PublishMessageStub        func(string, string, any) error
	publishMessageMutex       sync.RWMutex
	publishMessageArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 any
	}
	publishMessageReturns struct {
		result1 error
	}
	publishMessageReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProducer) PublishMessage(arg1 string, arg2 string, arg3 any) error {
	fake.publishMessageMutex.Lock()
	ret, specificReturn := fake.publishMessageReturnsOnCall[len(fake.publishMessageArgsForCall)]
	fake.publishMessageArgsForCall = append(fake.publishMessageArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 any
	}{arg1, arg2, arg3})
	stub := fake.PublishMessageStub
	fakeReturns := fake.publishMessageReturns
	fake.recordInvocation("PublishMessage", []interface{}{arg1, arg2, arg3})
	fake.publishMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProducer) PublishMessageCallCount() int {
	fake.publishMessageMutex.RLock()
	defer fake.publishMessageMutex.RUnlock()
	return len(fake.publishMessageArgsForCall)
}

func (fake *FakeProducer) PublishMessageCalls(stub func(string, string, any) error) {
	fake.publishMessageMutex.Lock()
	defer fake.publishMessageMutex.Unlock()
	fake.PublishMessageStub = stub
}

func (fake *FakeProducer) PublishMessageArgsForCall(i int) (string, string, any) {
	fake.publishMessageMutex.RLock()
	defer fake.publishMessageMutex.RUnlock()
	argsForCall := fake.publishMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProducer) PublishMessageReturns(result1 error) {
	fake.publishMessageMutex.Lock()
	defer fake.publishMessageMutex.Unlock()
	fake.PublishMessageStub = nil
	fake.publishMessageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProducer) PublishMessageReturnsOnCall(i int, result1 error) {
	fake.publishMessageMutex.Lock()
	defer fake.publishMessageMutex.Unlock()
	fake.PublishMessageStub = nil
	if fake.publishMessageReturnsOnCall == nil {
		fake.publishMessageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishMessageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProducer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.publishMessageMutex.RLock()
	defer fake.publishMessageMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProducer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ messagequeue.Producer = new(FakeProducer)
